name: Build Linux

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      CONTAINER_SLUG:
        required: true

jobs:
  build-app-linux:
    name: 🚀 Build Application - Linux
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - name: 🏗️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./**/yarn.lock
          cache: yarn
          check-latest: true
          node-version: 20.x
      - name: 🏗️ Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          architecture: "x64"
          cache: "pip"
          check-latest: true
          python-version: "3.12"
      - name: 🏗️ Install dependencies
        run: |
          sudo apt update
          sudo apt install libavahi-compat-libdnssd-dev libxtst-dev libpng++-dev libxext-dev libxss-dev libopengl0
          wget https://github.com/goreleaser/nfpm/releases/download/v2.11.3/nfpm_amd64.deb
          sudo apt install ./nfpm_amd64.deb
          rm ./nfpm_amd64.deb
      - name: 🏗️ Install packages
        run: |
          yarn install:all:ci
      - name: 📦 Package
        run: |
          yarn package
      - name: 📦 Archive
        run: |
          tar -czvf out.tar.gz out
      - name: ⬆️ Upload Artifacts - Output
        uses: actions/upload-artifact@v4.6.1
        with:
          name: linux-out
          path: out.tar.gz
      - name: 🚀 Create apk file
        run: |
          nfpm package --config nfpm.yml --packager apk
      - name: ⬆️ Upload Artifacts - apk
        uses: actions/upload-artifact@v4.6.1
        with:
          name: linux-apk
          path: "*.apk"
      - name: 🚀 Create deb file
        run: |
          nfpm package --config nfpm.yml --packager deb
      - name: ⬆️ Upload Artifacts - deb
        uses: actions/upload-artifact@v4.6.1
        with:
          name: linux-deb
          path: "*.deb"
      - name: 🚀 Create rpm file
        run: |
          nfpm package --config nfpm.yml --packager rpm
      - name: ⬆️ Upload Artifacts - rpm
        uses: actions/upload-artifact@v4.6.1
        with:
          name: linux-rpm
          path: "*.rpm"
  build-container:
    name: 🚀 Build Container - ${{ matrix.architecture }}
    runs-on: ubuntu-latest
    needs:
      - build-app-linux
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - amd64
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - name: ⤵️ Download Artifact - deb
        uses: actions/download-artifact@v4.1.9
        with:
          name: linux-deb
      - name: 🏗️ Set up build cache
        id: cache
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cache
          key: docker-${{ github.ref }}-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            docker-${{ github.ref }}-${{ matrix.architecture }}
      - name: 🏗️ Set up QEMU
        uses: docker/setup-qemu-action@v3.5.0
      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0
      - name: ℹ️ Compose build flags
        id: flags
        run: |
          echo "::set-output name=date::$(date +"%Y-%m-%dT%H:%M:%SZ")"
          from=$(jq --raw-output ".build_from.${{ matrix.architecture }}" "build.json")
          echo "::set-output name=from::${from}"
          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
            echo "::set-output name=platform::linux/amd64"
          else
            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
            exit 1
          fi
      - name: 🚀 Build
        uses: docker/build-push-action@v6.14.0
        with:
          push: false
          context: .
          file: Dockerfile
          cache-from: |
            type=local,src=/tmp/.docker-cache
            ghcr.io/timmo001/${{ secrets.CONTAINER_SLUG }}/${{ matrix.architecture }}:edge
          cache-to: type=local,mode=max,dest=/tmp/.docker-cache
          platforms: ${{ steps.flags.outputs.platform }}
          build-args: |
            BUILD_ARCH=${{ matrix.architecture }}
            BUILD_DATE=${{ steps.flags.outputs.date }}
            BUILD_FROM=${{ steps.flags.outputs.from }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
            BUILD_VERSION=edge
