---
name: Build msbuild Windows

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      code-path:
        required: false
        type: string
        default: "."
      nuget-version:
        description: "NuGet version"
        required: false
        type: string
        default: "latest"
      output-name:
        required: true
        type: string
      output-path:
        required: true
        type: string
      package:
        required: true
        type: string

jobs:
  build-msbuild-windows:
    name: 🚀 Build Application - Windows
    runs-on: windows-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.head_ref }}
      - name: 🏗️ Set up MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3
        with:
          msbuild-architecture: x64
      - name: 🏗️ Set up NuGet
        uses: nuget/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4
        with:
          nuget-version: ${{ inputs.nuget-version }}
      - name: 🏗️ Build
        run: |
          cd ${{ inputs.code-path }}
          nuget restore ${{ inputs.package }}
          msbuild ${{ inputs.package }} `
            -t:rebuild `
            -verbosity:diag `
            -property:Configuration=Release
      - name: ⬆️ Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.output-name }}
          path: ${{ inputs.output-path }}
