---
name: Build msbuild Linux

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      code-path:
        required: false
        type: string
        default: "."
      output-name:
        required: true
        type: string
      output-path:
        required: true
        type: string
      package:
        required: true
        type: string

jobs:
  build-msbuild-windows:
    name: 🚀 Build Application - Windows
    runs-on: windows-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.head_ref }}
      - name: 🏗️ Set up MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64
      - name: 🏗️ Set up NuGet
        uses: nuget/setup-nuget@v3
        with:
          nuget-version: ${{ matrix.nuget }}
      - name: 🏗️ Build
        run: |
          cd ${{ inputs.code-path }}
          nuget restore ${{ inputs.package }}
          msbuild ${{ inputs.package }} `
            -t:rebuild `
            -verbosity:diag `
            -property:Configuration=Release
      - name: ⬆️ Upload Artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ inputs.output-name }}
          path: ${{ inputs.output-path }}
