---
name: Build Windows

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true

jobs:
  build-app-windows:
    name: 🚀 Build Application - Windows
    runs-on: self-hosted
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.head_ref }}
      - name: 🏗️ Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install:all:ci
      - name: 🏗️ Add console hide command
        run: |
          Add-Content -Path .\src\index.ts -Value $(Get-Content -Path .\scripts\windowsConsoleHide.js)
      - name: 📦 Package
        run: |
          yarn package
      - name: 📦 Archive
        run: |
          Compress-Archive -DestinationPath out.zip -Path out
      - name: ⬆️ Upload Artifacts - Output
        uses: actions/upload-artifact@v7.0.0
        with:
          name: windows-out
          path: out.zip
      - name: 🚀 Create setup file
        uses: joncloud/makensis-action@v5.0
        with:
          script-file: "installer-${{ inputs.name }}.nsi"
      - name: ⬆️ Upload Artifacts - Setup
        uses: actions/upload-artifact@v7.0.0
        with:
          name: windows-setup
          path: "*setup.exe"
