---
name: Build and Deploy Android Application

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      java-version:
        description: "Java (Temurin) version"
        required: false
        type: string
        # renovate: datasource=java-version depName=java
        default: "25.0.3+9.0.LTS"
      code-path:
        required: false
        type: string
        default: "."
      package-name:
        required: true
        type: string
    secrets:
      ALIAS:
        required: true
      KEY_PASSWORD:
        required: true
      SERVICE_ACCOUNT:
        required: true
      SIGN_KEY:
        required: true
      STORE_KEY_PASSWORD:
        required: true

jobs:
  build-container:
    name: 🚀 Build Android Application
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}
      - name: 🏗️ Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          cache: gradle
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}
      - name: 🏗️ Grant execute permission for gradlew
        run: |
          cd ${{ inputs.code-path }}
          chmod +x gradlew
      - name: 🏭 Run Tests
        run: |
          cd ${{ inputs.code-path }}
          ./gradlew test
      - name: 🏭 Build Project
        run: |
          cd ${{ inputs.code-path }}
          ./gradlew build
      - name: ↗ Upload APK - Debug
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: app-debug-apk
          path: ${{ inputs.code-path }}/app/build/outputs/apk/debug/app-debug.apk
      - name: 🏭 Build Release AAB
        run: |
          cd ${{ inputs.code-path }}
          ./gradlew bundle
      - name: ↗ Upload AAB - Debug
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: app-debug-aab
          path: ${{ inputs.code-path }}/app/build/outputs/bundle/debug/app-debug.aab
      - name: 🖋 Sign AAB
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407 # v1
        with:
          alias: ${{ secrets.ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
          releaseDirectory: ${{ inputs.code-path }}/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
        env:
          BUILD_TOOLS_VERSION: "33.0.0"
      - name: ↗ Upload AAB - Release
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: app-release-aab
          path: ${{ inputs.code-path }}/app/build/outputs/bundle/release/app-release.aab
      - name: ↗ Upload APK - Release Asset
        if: ${{ github.event_name == 'release' }}
        uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f # v1.3
        env:
          GHR_PATH: ${{ inputs.code-path }}/app/build/outputs/apk/debug/app-debug.apk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ↗ Upload AAB - Release Asset
        if: ${{ github.event_name == 'release' }}
        uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f # v1.3
        env:
          GHR_PATH: ${{ inputs.code-path }}/app/build/outputs/bundle/release/app-release.aab
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 📢 Deploy to Play Store - Internal Sharing
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: r0adkll/upload-google-play@e738b9dd8f2476ea806d921b64aacd24f34515a5 # v1
        with:
          packageName: ${{ inputs.package-name }}
          releaseFiles: ${{ inputs.code-path }}/app/build/outputs/bundle/release/app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          track: internalsharing
      - name: 📢 Deploy to Play Store - Beta
        if: ${{ github.event_name == 'release' && github.event.release.prerelease == true }}
        uses: r0adkll/upload-google-play@e738b9dd8f2476ea806d921b64aacd24f34515a5 # v1
        with:
          packageName: ${{ inputs.package-name }}
          releaseFiles: ${{ inputs.code-path }}/app/build/outputs/bundle/release/app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          track: beta
      - name: 📢 Deploy to Play Store - Production
        if: ${{ github.event_name == 'release' && github.event.release.prerelease == false }}
        uses: r0adkll/upload-google-play@e738b9dd8f2476ea806d921b64aacd24f34515a5 # v1
        with:
          packageName: ${{ inputs.package-name }}
          releaseFiles: ${{ inputs.code-path }}/app/build/outputs/bundle/release/app-release.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          track: production
