---
name: "Dependency Review"

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4.2.0
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
