---
name: Fallow

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      root:
        description: "Root directory to analyze"
        required: false
        type: string
        default: "."

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fallow:
    name: Fallow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Run Fallow on changed files
        if: github.event_name != 'workflow_dispatch'
        uses: fallow-rs/fallow@6c3760fff5eb6d5853a2fca0180e491b5e2eef36 # v3.5.1
        with:
          root: ${{ inputs.root }}
          format: sarif
          changed-since: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
      - name: Run Fallow full scan
        if: github.event_name == 'workflow_dispatch'
        uses: fallow-rs/fallow@6c3760fff5eb6d5853a2fca0180e491b5e2eef36 # v3.5.1
        with:
          root: ${{ inputs.root }}
          format: sarif
