---
name: HACS Validate

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: false
        type: string
        # renovate: datasource=node-version depName=node versioning=node
        default: "26.5.0"
      hacs-category:
        description: "HACS category for validation"
        required: false
        type: string
        default: "plugin"
      submodules:
        description: "Checkout submodules recursively"
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: HACS Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: ${{ inputs.submodules && 'recursive' || 'false' }}
      - name: Enable corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: ${{ inputs.hacs-category }}
