---
name: Lint - JSONLint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_call:
  workflow_dispatch:

jobs:
  lint-jsonlint:
    name: 👕 JSONLint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
      - name: 🚀 Run JSONLint
        run: |
          sudo apt install -y jsonlint
          while IFS= read -r -d '' file; do
            if ! jsonlint-php -q "$file"; then
              FAILED=1
            else
              echo "$file OK"
            fi
          done < <(find ./ -type f -name "*.json" -print0)
          if [ "${FAILED}" = "1" ]; then
            exit 1
          fi
