---
name: Lint general

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      actionlint-version:
        description: "actionlint version to use"
        required: false
        type: string
        default: "1.7.12"
      lint-markdown:
        description: "Run markdownlint"
        required: false
        type: boolean
        default: true
      lint-yaml:
        description: "Run yamllint"
        required: false
        type: boolean
        default: true
      lint-actions:
        description: "Run actionlint"
        required: false
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    if: ${{ inputs.lint-markdown }}
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - name: Lint markdown
        run: bunx markdownlint-cli .

  lint-yaml:
    if: ${{ inputs.lint-yaml }}
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - name: Lint YAML
        run: bunx yamllint .

  lint-github-actions:
    if: ${{ inputs.lint-actions }}
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download actionlint
        run: |
          curl -sL "https://github.com/rhysd/actionlint/releases/download/v${{ inputs.actionlint-version }}/actionlint_${{ inputs.actionlint-version }}_linux_amd64.tar.gz" \
            | tar xz -C /usr/local/bin actionlint
      - name: Lint GitHub Actions workflows
        run: actionlint -shellcheck= -pyflakes=
