name: Lint - MarkdownLint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_call:
  workflow_dispatch:

jobs:
  lint-markdownlint:
    name: 👕 MarkdownLint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
      - name: 🚀 Run mdl
        uses: actionshub/markdownlint@6c82ff529253530dfbf75c37570876c52692835f # main
