---
name: "Lint - Pylint"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        required: false
        type: string
        # renovate: datasource=python-version depName=python versioning=python
        default: "3.14.6"
      code-path:
        required: false
        type: string
        default: "."
      module-name:
        required: false
        type: string
        default: "."
      pre-run-command:
        required: false
        type: string
      pre-install-command:
        required: false
        type: string

jobs:
  lint-pylint:
    name: 👕 Run Pylint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.head_ref }}
      - name: 🏗️ Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          architecture: "x64"
          cache: "pip"
          check-latest: true
          python-version: ${{ inputs.python-version }}
      - name: 🏗️ Install setuptools, wheel, pylint
        run: |
          pip install --upgrade setuptools wheel pylint
      - name: 🚀 Run pre-install-command
        if: ${{ inputs.pre-install-command }}
        run: |
          cd ${{ inputs.code-path }}
          ${{ inputs.pre-install-command }}
      - name: 📦 Install
        run: |
          cd ${{ inputs.code-path }}
          pip install .
      - name: 🚀 Run pre-run-command
        if: ${{ inputs.pre-run-command }}
        run: |
          cd ${{ inputs.code-path }}
          ${{ inputs.pre-run-command }}
      - name: 🚀 Run Pylint
        run: |
          cd ${{ inputs.code-path }}
          pylint ${{ inputs.module-name }}
