name: Lint - Markdown Links

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_call:
  workflow_dispatch:

jobs:
  lint-markdown-links:
    name: 👕 Markdown Links
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.head_ref }}
      - name: 🚀 Run Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
        with:
          use-quiet-mode: no
          use-verbose-mode: no
          config-file: mlc_config.json
          folder-path: .github
          file-path: ./README.md
          max-depth: -1
          check-modified-files-only: no
          base-branch: master
          file-extension: .md
