---
name: "Lint - Black"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      code-path:
        required: false
        type: string
        default: "."
      pre-run-command:
        required: false
        type: string

jobs:
  lint-black:
    name: 👕 Run Black
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🚀 Run pre-run-command
        if: ${{ inputs.pre-run-command }}
        run: ${{ inputs.pre-run-command }}
        working-directory: ${{ inputs.code-path }}
      - name: 🚀 Run black
        run: |
          python -V
          pip -V
          pip install --upgrade uv
          uv venv
          uv pip install --upgrade black
          black --check .
        working-directory: ${{ inputs.code-path }}
