---
name: "Lint - ESLint"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: false
        type: string
        # renovate: datasource=node-version depName=node versioning=node
        default: "26.5.0"
      code-path:
        required: false
        type: string
        default: "."
      use-bun:
        required: false
        type: boolean
        default: false
      use-pnpm:
        required: false
        type: boolean
        default: false

jobs:
  lint-eslint:
    name: 👕 ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
      - name: 🥖 Install Bun
        if: ${{ inputs.use-bun }}
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: latest
      - name: 🍎 Install pnpm
        if: ${{ inputs.use-pnpm }}
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: 🏗️ Set up Node.js (pnpm)
        if: ${{ inputs.use-pnpm }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache-dependency-path: ${{ inputs.code-path || '.' }}/**/pnpm-lock.yaml
          cache: pnpm
          check-latest: true
          node-version: ${{ inputs.node-version }}
      - name: 🏗️️ Set up Node.js (yarn)
        if: ${{ !inputs.use-bun && !inputs.use-pnpm }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache-dependency-path: ${{ inputs.code-path || '.' }}/**/yarn.lock
          cache: yarn
          check-latest: true
          node-version: ${{ inputs.node-version }}
      - name: ⤵️ Install dependencies
        run: |
          if [ "${{ inputs.use-pnpm }}" = "true" ]; then
              pnpm install
          elif [ "${{ inputs.use-bun }}" = "true" ]; then
              bun install
          else
              yarn install
          fi
        working-directory: ${{ inputs.code-path }}
      - name: 🚀 Run ESLint
        run: |
          if grep -q "next lint" "package.json"; then
              echo "next lint is present in package.json"
              if [ "${{ inputs.use-pnpm }}" = "true" ]; then
                  pnpm run lint
              elif [ "${{ inputs.use-bun }}" = "true" ]; then
                  bun run lint
              else
                  yarn lint
              fi
          else
              echo "next lint is not found in package.json"
              if [ "${{ inputs.use-pnpm }}" = "true" ]; then
                  pnpm run eslint
              elif [ "${{ inputs.use-bun }}" = "true" ]; then
                  bun run eslint
              else
                  yarn eslint
              fi
          fi
        env:
          SKIP_ENV_VALIDATION: true
        working-directory: ${{ inputs.code-path }}
