---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions:
  contents: read

jobs:
  release-drafter:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🖊️ Create draft release
        id: release_drafter
        uses: release-drafter/release-drafter@c345907820e0396f6f44bcfd9ac4763325f8feb0 # v7.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
