---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions:
  contents: read

jobs:
  release-drafter:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🖊️ Create draft release
        id: release_drafter
        uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
