---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions:
  contents: read

jobs:
  release-drafter:
    name: ✏️ Draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🖊️ Create draft release
        id: release_drafter
        uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
