name: Stale Repositories

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "3 2 1 * *"
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Stale Repository Identifier
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.head_ref }}
      - name: 🚀 Run stale repos tool
        id: stale-repos
        uses: docker://ghcr.io/github/stale_repos:v1
        env:
          EXEMPT_TOPICS: "keep,template"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          INACTIVE_DAYS: 180
      - name: 🚀 Print output of stale repos tool
        run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"
      - name: 🚀 Create issues for stale repos
        uses: actions/github-script@v8
        with:
          script: |
            const repos = ${{ steps.stale-repos.outputs.inactiveRepos }}
            for (const repo of repos) {
              console.log(repo);
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Stale repository: ' + repo.url,
                body: 'This repo is over 180 days old. Please contact the owner to make it active again.\n\n' + repo.url,
              });
              console.log(issue);
            }
          github-token: ${{ secrets.GH_TOKEN }}
