name: Stale Repositories

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "3 2 1 * *"
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Stale Repository Identifier
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: 🚀 Run stale_repos tool
        id: stale-repos
        uses: docker://ghcr.io/github/stale_repos:v1
        env:
          EXEMPT_TOPICS: "keep,template"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # INACTIVE_DAYS: 182
          INACTIVE_DAYS: 120
      - name: Print output of stale_repos tool
        run: echo "${{ steps.stale-repos.outputs.inactiveRepos }}"
      - uses: actions/github-script@v6
        with:
          script: |
            const repos = ${{ steps.stale-repos.outputs.inactiveRepos }}
            for (const repo of repos) {
              console.log(repo);
              const issue = await github.rest.issues.create({
                owner: '{{ github.repository_owner }}',
                repo: '{{ github.event.repository.name }}',
                title: 'Stale repo' + repo.url,
                body: 'This repo is stale. Please contact the owner to make it active again.',
              });
              console.log(issue);
            }
          github-token: ${{ secrets.GH_TOKEN }}
